---
environment: production
# Specify either port or socket 
port: 3000
#socket: tmp/sockets/thin.sock
servers: 3
tag: sinatra-websocket-rack-example
pid: tmp/pids/thin.pid
log: log/thin.log
daemonize: true
